### ISSUE TITLE
Obtain Speaker embedding

### ISSUE THREAD

**Issue by longkhanh-fam** [choijeongsoo/lip2speech-unit#10]
Im reproduce your result on LRS2 dataset. What is the file that you use to extract the speaker embedding and how long for that file?

**Comment by choijeongsoo** [comment]
We followed [Real-Time-Voice-Cloning](https://github.com/CorentinJ/Real-Time-Voice-Cloning) to extract speaker embedding and [SVTS](https://arxiv.org/abs/2205.02058) for evaluation protocol.

The pretrained `encoder` model can be found [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models).

You can also contact us by email at jeongsoo.choi@kaist.ac.kr to obtain our LRS2 test samples.

**Comment by longkhanh-fam** [comment]
Thank you,  @choijeongsoo . I have reached out via email for the LRS2 test samples as suggested.
Again, thank you so much for your quick and helpful response! I really appreciate it.
