### ISSUE TITLE
The omegaconf version issue in Reasoning One

### ISSUE THREAD

**Issue by cwhm123** [choijeongsoo/lip2speech-unit#12]
![image](https://github.com/user-attachments/assets/da7a00a3-aba9-4bf6-ba1a-4e305566456c)

ImportError: cannot import name 'II' from 'omegaconf' (/home/wenhui/anaconda3/envs/lip2speech/lib/python3.10/site-packages/omegaconf/__init__.py)
ImportError: cannot import name 'Config' from 'omegaconf' (/home/wenhui/anaconda3/envs/lip2speech/lib/python3.10/site-packages/omegaconf/__init__.py)
All are carried out according to the steps in the README

**Comment by choijeongsoo** [comment]
Hi, could please try `omegaconf==2.0.6` and `hydra-core==1.0.7`?
