### ISSUE TITLE
Training problems using Vox

### ISSUE THREAD

**Issue by cwhm123** [choijeongsoo/lip2speech-unit#15]
Can this model be trained using VoxCeleb2? I see that its preprocessing method is similar to LRE3, but there are issues with label.list. VoxCeleb2 does not have label.list. How can this be addressed

**Comment by choijeongsoo** [comment]
You could use dummy text for label.list since our model doesn't use label data.
I’ll check and update the code to remove the dependency when time allows.

**Comment by cwhm123** [comment]
OK Thank you for your reply
